package dev.rgbpulse.gboard;

// Generated by embed_shader.py; edit the files under shaders/.
final class ShaderCode {
    static final String FIELD =
        "// Ten curated pulses: eight key-local effects and two intentionally wide effects.\n" +
        "// Actual key bounds determine local footprint; summed alpha is capped for fast typing.\n" +
        "uniform float2 resolution;\n" +
        "uniform float time;\n" +
        "uniform float strength;\n" +
        "uniform float effectSize;\n" +
        "uniform float thickness;\n" +
        "uniform float style;\n" +
        "uniform float colorMode;\n" +
        "uniform float hue1;\n" +
        "uniform float hue2;\n" +
        "uniform float saturation;\n" +
        "uniform float4 taps[4];\n" +
        "uniform float4 keyBounds[4];\n" +
        "float3 hueRgb(float h){\n" +
        "    float3 w=abs(fract(float3(h)+float3(0,.6666667,.3333333))*6-3);\n" +
        "    return mix(float3(1),clamp(w-1,0,1),saturation);\n" +
        "}\n" +
        "float3 palette(float phase,float hue){\n" +
        "    if(colorMode>2.5&&colorMode<3.5)return mix(hueRgb(hue1),hueRgb(hue2),clamp(phase,0,1));\n" +
        "    if(colorMode>1.5&&colorMode<2.5)return hueRgb(hue1);\n" +
        "    return hueRgb(hue+phase*.12+(colorMode<.5?time*.015:0));\n" +
        "}\n" +
        "float band(float d,float w){return exp(-d*d/(w*w));}\n" +
        "half4 main(float2 frag){\n" +
        "    float energy=0;float3 light=float3(0);\n" +
        "    for(int i=0;i<4;i++){\n" +
        "        float age=taps[i].z;\n" +
        "        if(age>0&&age<1){\n" +
        "            float4 box=keyBounds[i];\n" +
        "            float2 halfSize=max((box.zw-box.xy)*.5,float2(1));\n" +
        "            float2 center=(box.xy+box.zw)*.5;\n" +
        "            float2 u=(frag-center)/halfSize;\n" +
        "            float2 a=abs(u);\n" +
        "            float envelope=smoothstep(0,.07,age)*(1-smoothstep(.35,1,age));\n" +
        "            float intensity=0;\n" +
        "            float width=.09*clamp(thickness,.6,1.6)*clamp(effectSize,.85,1.15);\n" +
        "            if(style<7.5){\n" +
        "                // Hard finite footprint, with a soft edge: no keyboard-sized local waves.\n" +
        "                float clip=(1-smoothstep(1.06,1.20,a.x))*(1-smoothstep(1.06,1.20,a.y));\n" +
        "                if(style<.5){\n" +
        "                    float edge=band(max(a.x,a.y)-.88,width);\n" +
        "                    float angle=atan(u.y,u.x)*.1591549+.5;\n" +
        "                    float travel=fract(angle-age);\n" +
        "                    intensity=edge*(.12+.88*exp(-travel*9));\n" +
        "                }else if(style<1.5){\n" +
        "                    float edge=band(max(a.x,a.y)-(.70+.22*age),width);\n" +
        "                    intensity=edge*smoothstep(.40,.72,min(a.x,a.y));\n" +
        "                }else if(style<2.5){\n" +
        "                    float head=-.9+1.8*age;\n" +
        "                    intensity=band(u.y-.83,width)*band(u.x-head,.38);\n" +
        "                }else if(style<3.5){\n" +
        "                    intensity=band(u.x+u.y-(-1.4+2.8*age),.15)*(1-smoothstep(.82,1,max(a.x,a.y)));\n" +
        "                }else if(style<4.5){\n" +
        "                    float reach=.5+.52*age;\n" +
        "                    float d=min(abs(u.x-reach)+a.y,abs(u.x+reach)+a.y);\n" +
        "                    d=min(d,min(a.x+abs(u.y-reach),a.x+abs(u.y+reach)));\n" +
        "                    intensity=1-smoothstep(.08,.22,d);\n" +
        "                }else if(style<5.5){\n" +
        "                    float r=length((frag-center)/max(1,min(halfSize.x,halfSize.y)));\n" +
        "                    intensity=band(r-(.12+.8*age),width);\n" +
        "                }else if(style<6.5){\n" +
        "                    intensity=band(a.x-(.15+.72*age),.12)*(1-smoothstep(.35,.85,a.y));\n" +
        "                }else{\n" +
        "                    intensity=.72*exp(-(u.x*u.x+u.y*u.y)/(.18+.3*sin(age*3.14159)));\n" +
        "                }\n" +
        "                intensity*=clip;\n" +
        "            }else{\n" +
        "                float2 p=(frag-taps[i].xy)/max(resolution.y,1);\n" +
        "                if(style<8.5)intensity=band(length(p)-age*1.25,.025);\n" +
        "                else intensity=band(p.y+age*.95-.16*sin(p.x*4+age*3),.075)*exp(-p.x*p.x/2);\n" +
        "            }\n" +
        "            float weight=clamp(intensity*envelope,0,1);\n" +
        "            energy+=weight;light+=palette(age+u.x*.1,taps[i].w)*weight;\n" +
        "        }\n" +
        "    }\n" +
        "    // This cap applies to the combined light, not separately per tap.\n" +
        "    float cap=style<7.5?.48:.28;\n" +
        "    float alpha=min(cap,energy*.55)*clamp(strength,0,1);\n" +
        "    return half4(clamp(light/max(energy,.0001),0,1)*alpha,alpha);\n" +
        "}\n";
    static final String FLUID =
        "// Magnetic fluid: metaball liquid that pools between the keys, stretches toward\n" +
        "// fingertips, splashes on taps and tilts with the device. The CPU simulation owns\n" +
        "// blob positions; this program renders the surface, lighting and touch glow.\n" +
        "// Uniform order matters for the desktop Skia test: scalar block first so the\n" +
        "// float4 arrays start 16-byte aligned.\n" +
        "uniform float2 resolution;\n" +
        "uniform float time;\n" +
        "uniform float strength;\n" +
        "uniform float hue;\n" +
        "uniform float hue2;\n" +
        "uniform float saturation;\n" +
        "uniform float tiltX;\n" +
        "uniform float tiltY;\n" +
        "uniform float ripple;\n" +
        "uniform float glow;\n" +
        "uniform float detail;\n" +
        "uniform float4 blobs[12];\n" +
        "uniform float4 touches[4];\n" +
        "float3 hueRgb(float h){\n" +
        "    float3 w=abs(fract(float3(h)+float3(0,.6666667,.3333333))*6-3);\n" +
        "    return mix(float3(1),clamp(w-1,0,1),clamp(saturation,0,1));\n" +
        "}\n" +
        "half4 main(float2 frag){\n" +
        "    float F=0;float2 grad=float2(0);float charge=0;\n" +
        "    for(int i=0;i<12;i++){\n" +
        "        float4 b=blobs[i];\n" +
        "        if(b.z<=0)continue;\n" +
        "        float2 d=frag-b.xy;\n" +
        "        float r2=b.z*b.z;\n" +
        "        float d2=dot(d,d)+r2*.18;\n" +
        "        float w=r2/d2;\n" +
        "        F+=w;grad-=2*w/d2*d;charge+=b.w*w;\n" +
        "    }\n" +
        "    float touchLight=0;\n" +
        "    for(int j=0;j<4;j++){\n" +
        "        float4 t=touches[j];\n" +
        "        if(t.z<=.01)continue;\n" +
        "        float2 d=frag-t.xy;\n" +
        "        float reach=max(resolution.y,1)*.16;\n" +
        "        float r2=reach*reach;\n" +
        "        float d2=dot(d,d)+r2*.25;\n" +
        "        float w=r2/d2*t.z*.8;\n" +
        "        // Fingers act as magnets: the surface itself leans toward them.\n" +
        "        F+=w;grad-=2*w/d2*d;\n" +
        "        touchLight+=t.z*exp(-dot(d,d)/(r2*.55));\n" +
        "    }\n" +
        "    float iso=1;\n" +
        "    float body=smoothstep(iso-.22,iso+.30,F);\n" +
        "    float halo=smoothstep(iso*.42,iso,F);\n" +
        "    if(body<=0&&halo<=0)return half4(0,0,0,0);\n" +
        "    float e=clamp(charge*.5+touchLight*.7,0,1);\n" +
        "    float3 nrm=normalize(float3(grad*2.2,7));\n" +
        "    float3 lightDir=normalize(float3(-tiltX*.8-.22,-tiltY*.8-.4,1));\n" +
        "    float diff=clamp(dot(nrm,lightDir),0,1);\n" +
        "    float spec=pow(clamp(dot(reflect(-lightDir,nrm),float3(0,0,1)),0,1),26);\n" +
        "    float shimmer=.5+.5*sin(F*(2.6+1.8*clamp(detail,0,2))-time*2.4+frag.x*.021+frag.y*.017);\n" +
        "    float3 deep=hueRgb(hue)*.16;\n" +
        "    float3 bodyColor=mix(deep,hueRgb(hue+.045*shimmer)*(.52+.34*diff),body);\n" +
        "    bodyColor+=hueRgb(hue2)*e*.38*body;\n" +
        "    float3 rim=mix(hueRgb(hue2),float3(1),.35);\n" +
        "    float3 color=bodyColor+rim*spec*(.5+.5*e)+float3(1)*touchLight*.10*clamp(ripple,0,2);\n" +
        "    float alpha=(body*(.52+.34*diff)+halo*clamp(glow,0,2)*.14)*clamp(strength,0,1);\n" +
        "    alpha=min(alpha,.88*clamp(strength,0,1));\n" +
        "    return half4(clamp(color,0,1)*alpha,alpha);\n" +
        "}\n";
}
