package dev.rgbpulse.gboard;

// Generated by embed_shader.py; edit shaders/field.agsl.
final class ShaderCode {
    static final String FIELD =
        "// RGB Pulse 6: expanding liquid waves only. Hologram tiles retained from v5.\n" +
        "// No image inputs, sampled keyboard content, masks, sprites or particles.\n" +
        "uniform float2 resolution;\n" +
        "uniform float time;\n" +
        "uniform float strength;\n" +
        "uniform float effectSize;\n" +
        "uniform float thickness;\n" +
        "uniform float style;\n" +
        "uniform float colorMode;\n" +
        "uniform float hue1;\n" +
        "uniform float hue2;\n" +
        "uniform float saturation;\n" +
        "uniform float4 taps[4];\n" +
        "\n" +
        "float3 hueRgb(float h) {\n" +
        "    float3 wave=abs(fract(float3(h)+float3(0.0,0.6666667,0.3333333))*6.0-3.0);\n" +
        "    return mix(float3(1.0),clamp(wave-1.0,0.0,1.0),saturation);\n" +
        "}\n" +
        "float3 palette(float f,float h) {\n" +
        "    if(colorMode>1.5 && colorMode<2.5) {\n" +
        "        float3 c=hueRgb(hue1);\n" +
        "        return mix(c,float3(1.0),0.06+0.14*(0.5+0.5*sin(f*6.28318)));\n" +
        "    }\n" +
        "    if(colorMode>2.5 && colorMode<3.5)\n" +
        "        return mix(hueRgb(hue1),hueRgb(hue2),0.5+0.5*sin(f*6.28318));\n" +
        "    if(colorMode>0.5)return hueRgb(h+0.11*sin(f*4.0));\n" +
        "    return hueRgb(h+0.19*f+0.035*time);\n" +
        "}\n" +
        "// Quintic envelope: zero first and second derivatives at the endpoints.\n" +
        "float softEase(float value) {\n" +
        "    float t=clamp(value,0.0,1.0);\n" +
        "    return t*t*t*(t*(t*6.0-15.0)+10.0);\n" +
        "}\n" +
        "float bell(float v,float width) { return exp(-v*v/width); }\n" +
        "float crest(float d,float width) { float w=width*thickness; return exp(-d*d/(w*w)); }\n" +
        "\n" +
        "half4 main(float2 frag) {\n" +
        "    float height=max(resolution.y,1.0);\n" +
        "    float3 light=float3(0.0);float energy=0.0;\n" +
        "    for(int i=0;i<4;i++) {\n" +
        "        float age=taps[i].z;\n" +
        "        if(age>=0.0 && age<1.0) {\n" +
        "            float2 q=(frag-taps[i].xy)/height;\n" +
        "            float2 p=q/max(effectSize,.1);\n" +
        "            float r=length(p),angle=atan(p.y,p.x+.00001);\n" +
        "            float a=1.0-pow(1.0-age,2.0);\n" +
        "            float envelope=smoothstep(0.0,.055,age)*(1.0-smoothstep(.30,1.0,age));\n" +
        "            float3 color=float3(0.0);float intensity=0.0;\n" +
        "            if(style>18.5){\n" +
        "                envelope=softEase(age/.10)*(1.0-softEase((age-.45)/.55));\n" +
        "                color=palette(p.x*.25+age*.2,taps[i].w);\n" +
        "                if(style<19.5){\n" +
        "                    // Diamond echo: a geometric front rather than a circular wave.\n" +
        "                    float diamond=abs(p.x)+abs(p.y);\n" +
        "                    intensity=.65*crest(diamond-age*1.4,.055)+.25*crest(diamond-age*.85,.075);\n" +
        "                }else if(style<20.5){\n" +
        "                    // Velvet tide: broad, undulating horizontal fabric sweeps upward.\n" +
        "                    float tide=p.y+age*.9-.10*sin(p.x*5.0+age*4.0);\n" +
        "                    intensity=.65*crest(tide,.16)*exp(-p.x*p.x/.9);\n" +
        "                }else{\n" +
        "                    // Split horizon: two horizontal planes move away from the touch.\n" +
        "                    intensity=.65*crest(abs(p.y)-age*.65,.06)*exp(-p.x*p.x/1.2);\n" +
        "                }\n" +
        "            }else if(style>14.5) {\n" +
        "                // Four non-radial / non-ring geometries, all anchored to the touch.\n" +
        "                envelope=softEase(age/.12)*(1.0-softEase((age-.5)/.5));\n" +
        "                color=palette(age*.2+p.y*.15,taps[i].w);\n" +
        "                if(style<15.5){\n" +
        "                    // Lateral sweep: two broad vertical light sheets travel sideways.\n" +
        "                    float front=age*1.8;\n" +
        "                    intensity=.72*crest(abs(p.x)-front,.11)*exp(-p.y*p.y/ .25);\n" +
        "                }else if(style<16.5){\n" +
        "                    // Soft spotlight: stationary elliptical pool; breathes, never a ring.\n" +
        "                    float width=.14+.18*sin(age*3.14159);\n" +
        "                    intensity=.8*exp(-(p.x*p.x*.55+p.y*p.y)/(width*width));\n" +
        "                }else if(style<17.5){\n" +
        "                    // Crossing ribbons: two diagonal bands separate with a gentle sway.\n" +
        "                    float offset=.08+.7*age;\n" +
        "                    float bend=.06*sin(p.x*4.0-age*3.0);\n" +
        "                    float a1=crest(p.y-.48*p.x-offset+bend,.055);\n" +
        "                    float a2=crest(p.y+.48*p.x+offset-bend,.055);\n" +
        "                    intensity=.62*(a1+a2)*exp(-p.x*p.x/.9);\n" +
        "                    color=palette(p.x*.35+age*.2,taps[i].w);\n" +
        "                }else{\n" +
        "                    // Rising curtain: a wide horizontal wash climbs above the touch.\n" +
        "                    float front=-age*.95;\n" +
        "                    float edge=crest(p.y-front,.13);\n" +
        "                    float trail=exp(-max(0.0,p.y-front)*8.0)*smoothstep(front-.03,front+.03,p.y);\n" +
        "                    intensity=(.6*edge+.22*trail)*exp(-p.x*p.x/.5);\n" +
        "                }\n" +
        "            } else if(style>11.5) {\n" +
        "                // Material-inspired tonal light: broad surfaces, restrained detail.\n" +
        "                float R=.035+.82*age;\n" +
        "                float d=r-R;\n" +
        "                color=palette(age*.16,taps[i].w);\n" +
        "                envelope=softEase(age/.10)*(1.0-softEase((age-.45)/.55));\n" +
        "                if(style<12.5) {\n" +
        "                    // Material bloom: soft raised-surface illumination with a thin edge.\n" +
        "                    intensity=.50*(1.0-smoothstep(max(0.0,R-.16),R+.06,r))+.22*crest(d,.025);\n" +
        "                } else if(style<13.5) {\n" +
        "                    // Diffused ring: feathered halo without a hard neon core.\n" +
        "                    intensity=.65*crest(d,.065)+.16*crest(d,.15);\n" +
        "                } else {\n" +
        "                    // Tonal orbit: quiet broad arc, rotating once with a subtle full ring.\n" +
        "                    float arc=.5+.5*cos(angle-age*3.14159);\n" +
        "                    intensity=crest(d,.045)*(.20+.55*arc)+.12*crest(d,.12);\n" +
        "                }\n" +
        "            } else if(style<.5) {\n" +
        "                // Exact v5 Hologram tiles field, including original lifetime curve.\n" +
        "                float2 grid=p*8.0;\n" +
        "                float row=floor(grid.y/.8660254);\n" +
        "                grid.x+=mod(row,2.0)*.5;\n" +
        "                float2 cell=float2(fract(grid.x)-.5,mod(grid.y,.8660254)-.4330127);\n" +
        "                float edge=max(abs(cell.x)*.8660254+abs(cell.y)*.5,abs(cell.y));\n" +
        "                float border=bell(edge-.39,.0013);\n" +
        "                float front=.10+.95*a;\n" +
        "                float active=bell(r-front,.045);\n" +
        "                float flash=.65+.35*cos(floor(grid.x)*1.3+row*2.0+age*6.0);\n" +
        "                color=mix(palette(row*.22+floor(grid.x)*.18,taps[i].w),float3(1.0),border*.28);\n" +
        "                intensity=active*(.25*flash+border*.75);\n" +
        "            } else {\n" +
        "                // Cubic ease-out travel with a soft attack and a long, smooth release.\n" +
        "                float progress=1.0-pow(1.0-age,3.0);\n" +
        "                float R=.025+1.02*progress;\n" +
        "                float d=r-R;\n" +
        "                float attack=softEase(age/.07);\n" +
        "                envelope=attack*(1.0-softEase((age-.48)/.52));\n" +
        "                float hue=taps[i].w;\n" +
        "                // Modern, soft styles: thin bright cores, deep bloom, gradient hues.\n" +
        "                float sweep=angle*.15915+.5; // 0..1 around the circle\n" +
        "                if(style<1.5) {\n" +
        "                    // Neon halo: crisp thin ring + wide soft bloom, conic gradient.\n" +
        "                    float core=crest(d,.006),glow=crest(d,.05),haze=crest(d,.16);\n" +
        "                    color=mix(palette(sweep+age*.3,hue),float3(1.0),core*.6);\n" +
        "                    intensity=core*.95+glow*.45+haze*.18;\n" +
        "                } else if(style<2.5) {\n" +
        "                    // Liquid glass: refracting lens rim with specular highlight and chroma edge.\n" +
        "                    float wob=.012*sin(angle*3.0+age*6.0);\n" +
        "                    float dd=d+wob;\n" +
        "                    float rim=crest(dd,.012),inner=crest(dd+.05,.06);\n" +
        "                    float spec=pow(max(0.0,cos(angle+2.3)),14.0)*crest(dd+.02,.02);\n" +
        "                    float3 cA=palette(sweep,hue),cB=palette(sweep+.33,hue);\n" +
        "                    color=mix(mix(cA,cB,smoothstep(-.02,.02,dd)),float3(1.0),spec*.9+rim*.3);\n" +
        "                    intensity=rim*.75+inner*.22+spec;\n" +
        "                } else if(style<3.5) {\n" +
        "                    // Aurora ring: flowing, flickering curtain on a soft annulus.\n" +
        "                    float n=sin(angle*5.0+age*4.0)*.5+sin(angle*9.0-age*6.0)*.3;\n" +
        "                    float dd=d-n*.03;\n" +
        "                    float band=crest(dd,.045);\n" +
        "                    float curtain=.55+.45*sin(angle*14.0+n*3.0+age*5.0);\n" +
        "                    color=palette(sweep*1.5+n*.2+age*.2,hue);\n" +
        "                    intensity=band*(.35+.75*curtain)+crest(dd,.008)*.4;\n" +
        "                } else if(style<4.5) {\n" +
        "                    // Metaball blobs: liquid droplets orbit and merge on the ring.\n" +
        "                    float field=0.0;float3 acc=float3(0.0);\n" +
        "                    for(int k=0;k<6;k++){\n" +
        "                        float fk=float(k);\n" +
        "                        float ang=fk*1.0472+age*(1.5+fk*.2)*(mod(fk,2.0)*2.0-1.0);\n" +
        "                        float2 c=R*float2(cos(ang),sin(ang));\n" +
        "                        float2 dv=p-c;\n" +
        "                        float f=.0035/(dot(dv,dv)+.0006);\n" +
        "                        field+=f;acc+=palette(fk/6.0+age*.2,hue)*f;\n" +
        "                    }\n" +
        "                    float surf=smoothstep(.9,1.3,field);\n" +
        "                    float edge=crest(field-1.1,.25);\n" +
        "                    color=mix(acc/max(field,.001),float3(1.0),edge*.35);\n" +
        "                    intensity=surf*.7+edge*.35+crest(d,.05)*.15;\n" +
        "                } else if(style<5.5) {\n" +
        "                    // Gradient bloom: soft filled disc that expands and fades like a light burst.\n" +
        "                    float disc=1.0-smoothstep(R-.10,R+.02,r);\n" +
        "                    float edge=crest(d,.03);\n" +
        "                    color=mix(palette(r*1.4+sweep*.3,hue),float3(1.0),edge*.4);\n" +
        "                    intensity=disc*.35*(1.0-age)+edge*.7;\n" +
        "                } else if(style<6.5) {\n" +
        "                    // Prism ring: RGB split rings with subtle dispersion.\n" +
        "                    float rr=crest(d-.012,.010),gg=crest(d,.010),bb=crest(d+.012,.010);\n" +
        "                    float3 rgb=float3(rr,gg,bb);\n" +
        "                    float3 tint=palette(sweep+age*.2,hue);\n" +
        "                    color=clamp(mix(rgb*1.3,tint,.35),0.0,1.0);\n" +
        "                    intensity=max(rr,max(gg,bb))*.95+crest(d,.06)*.25;\n" +
        "                } else if(style<7.5) {\n" +
        "                    // Sonar pulse: evenly spaced soft echoes behind a bright leading edge.\n" +
        "                    float echoes=pow(.5+.5*cos((r*22.0-age*14.0)),6.0)*step(r,R);\n" +
        "                    float lead=crest(d,.008);\n" +
        "                    float fade=exp(-max(0.0,R-r)*4.0);\n" +
        "                    color=mix(palette(r+sweep*.2,hue),float3(1.0),lead*.5);\n" +
        "                    intensity=lead+echoes*fade*.5;\n" +
        "                } else if(style<8.5) {\n" +
        "                    // Silk wave: smooth undulating ribbon ring with sheen.\n" +
        "                    float wave=.035*sin(angle*6.0+age*7.0);\n" +
        "                    float dd=d+wave;\n" +
        "                    float ribbon=crest(dd,.022);\n" +
        "                    float sheen=pow(.5+.5*cos(angle*6.0+age*7.0+1.2),8.0);\n" +
        "                    color=mix(palette(sweep*2.0,hue),float3(1.0),sheen*ribbon*.6);\n" +
        "                    intensity=ribbon*(.6+.5*sheen)+crest(dd,.08)*.18;\n" +
        "                } else if(style<9.5) {\n" +
        "                    // Plasma burst: turbulent flame-like edge.\n" +
        "                    float t1=sin(angle*7.0+r*20.0-age*8.0)+sin(angle*11.0-age*10.0)*.6;\n" +
        "                    float dd=d-t1*.018;\n" +
        "                    float body=crest(dd,.035),hot=crest(dd,.009);\n" +
        "                    color=mix(palette(t1*.2+sweep,hue),float3(1.0),hot*.55);\n" +
        "                    intensity=body*.6+hot*.7;\n" +
        "                } else {\n" +
        "                    // Dual orbit: two rings counter-rotating with bright comet arcs.\n" +
        "                    float R2=R*.7;\n" +
        "                    float a1=pow(max(0.0,cos(angle-age*6.0)),10.0);\n" +
        "                    float a2=pow(max(0.0,cos(angle+age*7.0+3.14)),10.0);\n" +
        "                    float r1=crest(d,.008),r2=crest(r-R2,.008);\n" +
        "                    color=mix(palette(sweep+age*.3,hue),float3(1.0),(a1*r1+a2*r2)*.6);\n" +
        "                    intensity=r1*(.25+a1)+r2*(.25+a2)+crest(d,.05)*.12;\n" +
        "                }\n" +
        "                // Prevent wake tails leaking through the touch center at the beginning.\n" +
        "                intensity*=smoothstep(0.0,.018,r);\n" +
        "            }\n" +
        "            float weight=clamp(intensity*envelope,0.0,1.0);\n" +
        "            light+=color*weight;energy+=weight;\n" +
        "        }\n" +
        "    }\n" +
        "    float opacity=clamp((1.0-exp(-energy*1.6))*strength,0.0,1.0);\n" +
        "    float3 rgb=clamp(light/max(energy,.0001),0.0,1.0);\n" +
        "    return half4(rgb*opacity,opacity);\n" +
        "}\n";
}
