#!/usr/bin/env python3
"""Generate the Java shader constants from the checked-in AGSL sources.

Keeping this deterministic makes shader edits reviewable and prevents the APK from
silently using a stale embedded program.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TARGET = ROOT / "src" / "dev" / "rgbpulse" / "gboard" / "ShaderCode.java"
SOURCES = [("shaders/field.agsl", "FIELD")]


def java_literal(text):
    # Java string escaping, intentionally one source line per Java line for useful diffs.
    lines = text.splitlines(keepends=True)
    if not lines:
        raise SystemExit("shader source is empty")
    out = []
    for n, line in enumerate(lines):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")
        # Newline is represented in the Java literal, not emitted as a physical part of it.
        if escaped.endswith("\n"):
            escaped = escaped[:-1] + "\\n"
        out.append('        "' + escaped + ('" +' if n < len(lines) - 1 else '";'))
    return out


out = ["package dev.rgbpulse.gboard;", "", "// Generated by embed_shader.py; edit the files under shaders/."]
out.append("final class ShaderCode {")
for source, constant in SOURCES:
    text = (ROOT / source).read_text(encoding="utf-8")
    out.append("    static final String {} =".format(constant))
    out.extend(java_literal(text))
out.append("}")
TARGET.write_text("\n".join(out) + "\n", encoding="utf-8")
