#!/usr/bin/env python3
"""Generate the Java shader constant from the checked-in AGSL source.

Keeping this deterministic makes shader edits reviewable and prevents the APK from
silently using a stale embedded program.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
source = ROOT / "shaders" / "field.agsl"
target = ROOT / "src" / "dev" / "rgbpulse" / "gboard" / "ShaderCode.java"
text = source.read_text(encoding="utf-8")
# Java string escaping, intentionally one source line per Java line for useful diffs.
lines = text.splitlines(keepends=True)
if not lines:
    raise SystemExit("shader source is empty")
out = ["package dev.rgbpulse.gboard;", "", "// Generated by embed_shader.py; edit shaders/field.agsl.",
       "final class ShaderCode {", "    static final String FIELD ="]
for n, line in enumerate(lines):
    escaped = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")
    # Newline is represented in the Java literal, not emitted as a physical part of it.
    if escaped.endswith("\n"):
        escaped = escaped[:-1] + "\\n"
    out.append('        "' + escaped + ('" +' if n < len(lines) - 1 else '";'))
out += ["}", ""]
target.write_text("\n".join(out), encoding="utf-8")
